<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="MSTest" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sleeky.Todo.Application\Sleeky.Todo.Application.csproj" />
    <ProjectReference Include="..\..\src\Sleeky.Todo.Assistant\Sleeky.Todo.Assistant.csproj" />
    <ProjectReference Include="..\..\src\Sleeky.Todo.Domain\Sleeky.Todo.Domain.csproj" />
  </ItemGroup>

</Project>
