import { defineConfig, devices } from '@playwright/test'

import { databaseName } from './e2e/database-name.ts'

export default defineConfig({
  testDir: './e2e',
  // The README's images are regenerated by a spec that photographs states the
  // suite already covers. It is a capture, not a test, so it stays out of the
  // ordinary run and is asked for by name through `yarn screenshots`.
  testIgnore: process.env.CAPTURE_SCREENSHOTS ? [] : ['**/screenshots.spec.ts'],
  globalSetup: './e2e/global-setup.ts',
  globalTeardown: './e2e/global-teardown.ts',
  fullyParallel: false,
  forbidOnly: Boolean(process.env.CI),
  retries: process.env.CI ? 2 : 0,
  timeout: 60_000,
  // One worker everywhere, not just in CI. Every spec shares one database, so
  // running files in parallel would let one test's cleanup reach into another's
  // data — and a local run that behaves differently from CI is how an ordering
  // bug reaches CI in the first place.
  workers: 1,
  // CI annotates the pull request through the github reporter, keeps JUnit for
  // the run summary, and writes the HTML report as an artifact rather than
  // trying to open it on a machine with no browser.
  reporter: process.env.CI
    ? [
        ['github'],
        ['junit', { outputFile: 'test-results/junit.xml' }],
        ['html', { open: 'never' }],
      ]
    : 'html',
  use: {
    baseURL: 'http://127.0.0.1:5173',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: [
    {
      command: 'dotnet run --project ../Sleeky.Todo.Api --launch-profile https',
      url: 'https://localhost:7238/health',
      ignoreHTTPSErrors: true,
      reuseExistingServer: false,
      timeout: 120_000,
      env: {
        ...process.env,
        MongoDb__DatabaseName: databaseName,
      },
    },
    // An OpenAI-compatible endpoint the specs write the replies for. The
    // assistant reaches self-hosted models through a configurable base URL, so
    // this needs no production seam: a turn runs through the same client, loop,
    // and tool layer a real provider would.
    {
      command: 'node e2e/stub-provider.mjs',
      url: 'http://127.0.0.1:4599/__health',
      reuseExistingServer: false,
      timeout: 30_000,
    },
    {
      command: 'corepack yarn dev --host 127.0.0.1',
      url: 'http://127.0.0.1:5173',
      reuseExistingServer: false,
      timeout: 60_000,
    },
  ],
})
