<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sleeky.Todo.Application\Sleeky.Todo.Application.csproj" />
    <ProjectReference Include="..\Sleeky.Todo.Assistant\Sleeky.Todo.Assistant.csproj" />
    <ProjectReference Include="..\Sleeky.Todo.Infrastructure\Sleeky.Todo.Infrastructure.csproj" />
  </ItemGroup>

</Project>
